apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      run: kuard
    name: kuard
  spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        run: kuard
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          chaos: "true"
        creationTimestamp: null
        labels:
          run: kuard
      spec:
        containers:
        - image: gcr.io/kuar-demo/kuard-amd64:blue
          imagePullPolicy: IfNotPresent
          name: kuard
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
          livenessProbe:
            httpGet:
              path: /healthy
              port: 8080
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      run: kuard
    name: kuard
    selfLink: /api/v1/namespaces/default/services/kuard
  spec:
    externalTrafficPolicy: Cluster
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      run: kuard
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer: {}
kind: List
